#  Copyright 2025 Monotype Imaging Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: "Create Label"
description: "Intended to draw attention to nightly failures and create PRs to fix them"
author: "Monotype"
inputs:
  label:
    description: "Name of the label to create"
    required: true
  color:
    description: "Color of the label to create"
    required: true
  description:
    description: "Description of the label to create"
    required: true
  force:
    description: "If true, will overwrite existing label with the same name"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    # Create label
    - name: Create label
      id: create-label
      shell: bash
      run: |
        set -e
        chmod +x ${{ github.action_path }}/createLabel.sh
        ${{ github.action_path }}/createLabel.sh
        exit $?
      env:
        GH_TOKEN: ${{ github.token }}
        LABEL: ${{ inputs.label }}
        COLOR: ${{ inputs.color }}
        DESCRIPTION: ${{ inputs.description }}
        FORCE: ${{ inputs.force }}
