#!/usr/bin/env bash

#  Copyright 2025 Monotype Imaging Inc.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#     http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


# Expects:
#   $VERSION - sem-ver version string
#   $GITHUB_ACTOR - user name of actor to tag with
#   $ACTOR_EMAIL - email of actor to tag with
#   $COMMIT_SHA - hash for commit to tag version to
#   $WORKFLOW_NAME - name of workflow which caused this to be called

# Validate required environment vars
if [[ ! -v VERSION ]]; then
  echo "::error::VERSION not specified"
  exit 1
elif [[ ! -v GITHUB_ACTOR ]]; then
  echo "::error::GITHUB_ACTOR not specified"
  exit 1
elif [[ ! -v ACTOR_EMAIL ]]; then
  echo "::error::ACTOR_EMAIL not specified"
  exit 1
elif [[ ! -v COMMIT_SHA ]]; then
  echo "::error::COMMIT_SHA not specified"
  exit 1
elif [[ ! -v WORKFLOW_NAME ]]; then
  echo "::error::WORKFLOW_NAME not specified"
  exit 1
fi

# Validate version is a semver
semverRegex="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"
if [[ ! $VERSION =~ $semverRegex ]]; then
  echo "::error::VERSION is not a semver version string"
  exit 1
fi

echo "::debug::Adding tag for ${VERSION}"

git config user.name "${GITHUB_ACTOR}"
git config user.email "${ACTOR_EMAIL}"
versionTag=v$VERSION

# Add tag if it doesn't yet exist.
if git show-ref "refs/tags/${versionTag}" >/dev/null 2>&1
then
  echo "::error::${versionTag} tag already exists, not adding new tag"
  exit 1
else
  git tag -a "${versionTag}" $COMMIT_SHA -m "Autogenerated by workflow: '${WORKFLOW_NAME}'.  Triggered by commit: ${COMMIT_SHA}"
  git push origin "${versionTag}"
  echo "::debug::${versionTag} tag added"
fi
