# @copyright 2024-2025 Monotype Imaging Inc.
#
# @file deny.toml
#
# @brief Configuration used for dependency checking with cargo-deny.
#
# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
yanked = "deny"
version = 2
ignore = []

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "allow" # "deny" # TODO: Change to "deny" when ready.

wildcards = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
version = 2
confidence-threshold = 0.8

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [] 

[sources.allow-org]
#github = ["Monotype"]