#  Copyright 2025 Monotype Imaging Inc.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#     http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: 'Update copyrights'
description: "Update copyright strings of all modified files to include current year"
author: 'Monotype'
inputs:
  base_branch:
    description: 'Name of the target branch used to determine changed files'
    required: true
  actor:
    description: 'Github id of actor to utilize for copyright update commit'
    required: true
  actor_email:
    description: 'Github email of actor to utilize for copyright update commit'
    required: true
outputs:
  copyright_commit_added:
    description: 'Boolean indicating if a commit was added for the copyright update'
    value: ${{ steps.create-copyright-commit.outputs.committed }}

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        chmod +x ${{ github.action_path }}/updateCopyrights.sh
        ${{ github.action_path }}/updateCopyrights.sh
        exit $?
      env:
        BASE_BRANCH: ${{ inputs.base_branch }}
    
    - name: Create commit with modified copyrights
      id: create-copyright-commit
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update copyrights to current year"
        author_name: ${{ inputs.actor }}
        author_email: ${{ inputs.actor_email }}
