# @copyright 2025 Monotype Imaging Inc.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#     http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @file builds.yml
#
# @brief A reusable workflow to be called from others for performing
#        builds.
#
on: 
  workflow_call:
    inputs:
      os:
        description: 'The operating system to build on'
        required: true
        type: string
      rust_version:
        description: 'The version of Rust to use'
        required: true
        type: string

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:

  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      # Add personal access token to github repository references to allow for
      # use of private repositories.
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_version }} 
      # Install rust dependencies from cache
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: Build all features
        run: cargo +${{ inputs.rust_version }} build --all-features
